
version : "3.7"

services :
    
    hk_nginx:
        
        container_name : hk_nginx
        image: nginx:1.13
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d
            
        depends_on:
        - app


        networks:
          - backend

    
    mongo_db_test:
        container_name: mongo_db_test
        image: mongo
        restart : always
        environment:
            MONGO_INITDB_DATABASE : admin
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: asd.123*-

        ports:
            - "27017:27017"

        networks:
            - backend
            

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - "8081:8081"

        environment:

              ME_CONFIG_BASICAUTH_USERNAME : root
              ME_CONFIG_MONGODB_ADMINUSERNAME: root
              ME_CONFIG_MONGODB_ADMINPASSWORD: asd.123*-
              ME_CONFIG_BASICAUTH_PASSWORD : asd.123*-
              ME_CONFIG_MONGODB_SERVER : mongo_db_test

        depends_on:
          - mongo_db_test

        networks:
            - backend


        
    app:
        restart : always
        build: .
        working_dir: /convertidor
       
        
        ports :
            - "8102:8102"
        
            
        depends_on:
            - mongo_db_test


        networks:
            - backend

        environment: # Pass environment variables to the service

            SPRING_DATA_MONGODB_DATABASE : admin
            SPRING_DATA_MONGODB_USERNAME : root
            SPRING_DATA_MONGODB_PASSWORD : asd.123*-
            SPRING_DATA_MONGODB_HOST: mongo_db_test
            SPRING_DATA_MONGODB_PORT: 27017



networks:
  backend:
      driver: bridge

